# Zone names are prefixed with numbers to allow proper handling of overlapping
# zone sources. More specific rules need to come before more generic rules. For
# details see
#
# https://access.redhat.com/solutions/5663141
#
puppeteers_firewall_strict_manage_backup_zone: true
puppeteers_firewall_strict_backup_zone: 10_backup
puppeteers_firewall_strict_backup_source_allow_ports: []
puppeteers_firewall_strict_backup_source_allow_services:
  - ssh

puppeteers_firewall_strict_manage_monitoring_zone: true
puppeteers_firewall_strict_monitoring_zone: 11_monitoring
puppeteers_firewall_strict_monitoring_source_allow_ports:
  - 9100/tcp
puppeteers_firewall_strict_monitoring_source_allow_services: []

puppeteers_firewall_strict_manage_vpn_zone: true
puppeteers_firewall_strict_vpn_zone: 50_vpn
puppeteers_firewall_strict_vpn_source_allow_ports: []
puppeteers_firewall_strict_vpn_source_allow_services:
  - ssh

puppeteers_firewall_strict_manage_intranet_zone: true
puppeteers_firewall_strict_intranet_zone: 51_intranet
puppeteers_firewall_strict_intranet_source_allow_ports: []
puppeteers_firewall_strict_intranet_source_allow_services: []

puppeteers_firewall_strict_assign_to_drop_zone: []
