---
- name: Validate zone parameters
  ansible.builtin.assert:
    that:
      - puppeteers_firewall_zone_name is string
      - "puppeteers_firewall_zone_source | ansible.utils.ipaddr is truthy"
      - puppeteers_firewall_zone_source_allow_ports is not string and puppeteers_firewall_zone_source_allow_ports is iterable
      - puppeteers_firewall_zone_source_allow_services is not string and puppeteers_firewall_zone_source_allow_services is iterable

- name: Create firewall zone
  ansible.posix.firewalld:
    zone: "{{ puppeteers_firewall_zone_name }}"
    state: present
    permanent: true
  notify: Reload firewalld to activate new zones

- name: Reload firewalld if necessary
  meta: flush_handlers

- name: Allow services from source
  ansible.posix.firewalld:
    state: enabled
    immediate: true
    permanent: true
    zone: "{{ puppeteers_firewall_zone_name }}"
    service: "{{ item }}"
  loop: "{{ puppeteers_firewall_zone_source_allow_services }}"

- name: Allow ports from source
  ansible.posix.firewalld:
    state: enabled
    immediate: true
    permanent: true
    zone: "{{ puppeteers_firewall_zone_name }}"
    port: "{{ item }}"
  loop: "{{ puppeteers_firewall_zone_source_allow_ports }}"

- name: Set zone source
  ansible.posix.firewalld:
    state: enabled
    immediate: true
    permanent: true
    zone: "{{ puppeteers_firewall_zone_name }}"
    source: "{{ puppeteers_firewall_zone_source }}"
