---
- name: Validate parameters
  ansible.builtin.assert:
    that:
      - puppeteers_firewall_strict_manage_backup_zone is boolean
      - puppeteers_firewall_strict_manage_monitoring_zone is boolean
      - puppeteers_firewall_strict_manage_vpn_zone is boolean
      - puppeteers_firewall_strict_manage_intranet_zone is boolean
      - puppeteers_firewall_strict_assign_to_drop_zone is not string and puppeteers_firewall_strict_assign_to_drop_zone is iterable

- name: Manage VPN zone
  ansible.builtin.import_role:
    name: puppeteers.firewall.zone
  vars:
    puppeteers_firewall_zone_name: "{{ puppeteers_firewall_strict_vpn_zone }}"
    puppeteers_firewall_zone_source: "{{ puppeteers_firewall_strict_vpn_source }}"
    puppeteers_firewall_zone_source_allow_ports: "{{ puppeteers_firewall_strict_vpn_source_allow_ports }}"
    puppeteers_firewall_zone_source_allow_services: "{{ puppeteers_firewall_strict_vpn_source_allow_services }}"
  when: puppeteers_firewall_strict_manage_vpn_zone 

- name: Manage backup zone
  ansible.builtin.import_role:
    name: puppeteers.firewall.zone
  vars:
    puppeteers_firewall_zone_name: "{{ puppeteers_firewall_strict_backup_zone }}"
    puppeteers_firewall_zone_source: "{{ puppeteers_firewall_strict_backup_source }}"
    puppeteers_firewall_zone_source_allow_ports: "{{ puppeteers_firewall_strict_backup_source_allow_ports }}"
    puppeteers_firewall_zone_source_allow_services: "{{ puppeteers_firewall_strict_backup_source_allow_services }}"
  when: puppeteers_firewall_strict_manage_backup_zone 

- name: Manage monitoring zone
  ansible.builtin.import_role:
    name: puppeteers.firewall.zone
  vars:
    puppeteers_firewall_zone_name: "{{ puppeteers_firewall_strict_monitoring_zone }}"
    puppeteers_firewall_zone_source: "{{ puppeteers_firewall_strict_monitoring_source }}"
    puppeteers_firewall_zone_source_allow_ports: "{{ puppeteers_firewall_strict_monitoring_source_allow_ports }}"
    puppeteers_firewall_zone_source_allow_services: "{{ puppeteers_firewall_strict_monitoring_source_allow_services }}"
  when: puppeteers_firewall_strict_manage_monitoring_zone 

- name: Manage intranet zone
  ansible.builtin.import_role:
    name: puppeteers.firewall.zone
  vars:
    puppeteers_firewall_zone_name: "{{ puppeteers_firewall_strict_intranet_zone }}"
    puppeteers_firewall_zone_source: "{{ puppeteers_firewall_strict_intranet_source }}"
    puppeteers_firewall_zone_source_allow_ports: "{{ puppeteers_firewall_strict_intranet_source_allow_ports }}"
    puppeteers_firewall_zone_source_allow_services: "{{ puppeteers_firewall_strict_intranet_source_allow_services }}"
  when: puppeteers_firewall_strict_manage_intranet_zone

- name: Assign interfaces to the drop zone to prevent leaks
  ansible.posix.firewalld:
    state: enabled
    zone: drop
    interface: "{{ item }}"
    immediate: true
    permanent: true
  when: item in ansible_facts['interfaces']
  loop: "{{ puppeteers_firewall_strict_assign_to_drop_zone }}"
